In [1]:
import cv2
import numpy as np

path = 'C:\VSCODE\Asset\ll_gray.bmp'
path2 = 'C:\VSCODE\Asset\ll_gray_png.png'
path3 = 'C:\VSCODE\Asset\est.bmp'

path4 = 'MerahPutih.jpg'

img3 = cv2.imread(path4)
print(img3.shape)
print(img3)
print(img3[10,110])

<>:4: SyntaxWarning: invalid escape sequence '\V'
<>:5: SyntaxWarning: invalid escape sequence '\V'
<>:6: SyntaxWarning: invalid escape sequence '\V'
<>:4: SyntaxWarning: invalid escape sequence '\V'
<>:5: SyntaxWarning: invalid escape sequence '\V'
<>:6: SyntaxWarning: invalid escape sequence '\V'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_153088\2914719801.py:4: SyntaxWarning: invalid escape sequence '\V'
  path = 'C:\VSCODE\Asset\ll_gray.bmp'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_153088\2914719801.py:5: SyntaxWarning: invalid escape sequence '\V'
  path2 = 'C:\VSCODE\Asset\ll_gray_png.png'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_153088\2914719801.py:6: SyntaxWarning: invalid escape sequence '\V'
  path3 = 'C:\VSCODE\Asset\est.bmp'


(408, 612, 3)
[[[ 37  31 238]
  [ 37  31 238]
  [ 37  31 238]
  ...
  [ 37  31 238]
  [ 37  31 238]
  [ 37  31 238]]

 [[ 37  31 238]
  [ 37  31 238]
  [ 37  31 238]
  ...
  [ 37  31 238]
  [ 37  31 238]
  [ 37  31 238]]

 [[ 37  31 238]
  [ 37  31 238]
  [ 37  31 238]
  ...
  [ 37  31 238]
  [ 37  31 238]
  [ 37  31 238]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[ 37  31 238]


In [2]:
cv2.imshow("testing",img3)
cv2.waitKey(0)

-1

In [3]:
#cropped
img4 = img3[:,100:200]
cv2.imshow('cropped',img4)
cv2.waitKey(0)

-1

In [4]:
#Resize by ratio
smol = cv2.resize(img3, (0,0), fx=0.5, fy=0.5)
large = cv2.resize(img3, (0,0), fx=1.5, fy=1.5)

cv2.imshow('smol', smol)
cv2.imshow('large', large)
cv2.waitKey(0)

-1

In [5]:
#Resize by Scale
print(img3.shape)
newSizeX, newSizeY = img3.shape[1]//4, img3.shape[0]//4


AfterResize = cv2.resize(img3,(newSizeX, newSizeX))

cv2.imshow('afterResize', AfterResize)
cv2.waitKey(0)

(408, 612, 3)


-1

In [6]:
#Invert
ImageM = cv2.bitwise_not(large)

cv2.imshow('invert', ImageM)
cv2.waitKey(0)

-1

In [7]:
#Rotate
ImageRot = cv2.rotate(img3, cv2.ROTATE_180)

cv2.imshow('rotate', ImageRot)
cv2.waitKey(0)

-1

In [8]:
print(img3.shape)

(408, 612, 3)


In [9]:
#Increasing Pixel Value
img12 = img3
value = 20
print(img12[0,0][0])
for i in range(408):
    for j in range(612):
        img12[i,j][0] = img12[i,j][0] + value
        img12[i,j][1] = img12[i,j][1] + value
        img12[i,j][2] = img12[i,j][2] + value

        if img12[i,j][0] > 255:
            img12[i,j][0] = 255
        if img12[i,j][0] < 0:
            img12[i,j][0] = 0
        if img12[i,j][1] > 255:
            img12[i,j][1] = 255
        if img12[i,j][1] < 0:
            img12[i,j][1] = 0
        if img12[i,j][2] > 255:
            img12[i,j][2] = 255
        if img12[i,j][2] < 0:
            img12[i,j][2] = 0

print(img12)
cv2.imshow('testing', img12)
cv2.waitKey(0)

37
[[[57 51  2]
  [57 51  2]
  [57 51  2]
  ...
  [57 51  2]
  [57 51  2]
  [57 51  2]]

 [[57 51  2]
  [57 51  2]
  [57 51  2]
  ...
  [57 51  2]
  [57 51  2]
  [57 51  2]]

 [[57 51  2]
  [57 51  2]
  [57 51  2]
  ...
  [57 51  2]
  [57 51  2]
  [57 51  2]]

 ...

 [[19 19 19]
  [19 19 19]
  [19 19 19]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[19 19 19]
  [19 19 19]
  [19 19 19]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[19 19 19]
  [19 19 19]
  [19 19 19]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]]


-1